### ISSUE TITLE
Solve Finding Prime Number

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/finding-prime-number#1]
Write a function in JavaScript that takes two integers as arguments (e.g. start and end) and returns an array containing all prime numbers in that range (including the start and end values ​​if they are prime). Prime numbers are those that are only divisible by 1 and themselves.

For example:

function encontrarNumerosPrimos(inicio, fin) {
  // Tu código aquí
}

const numerosPrimos = encontrarNumerosPrimos(10, 50);
console.log(numerosPrimos); // Debería mostrar [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

This exercise will challenge you to implement an algorithm to determine if a number is prime and then find all prime numbers in the specified range. You can use a for loop, a helper function to check if a number is prime, and an array to store the results. Good luck!

**Comment by kimiaRahimi** [comment]
@FarshadJanmohammadi
